### ISSUE TITLE
Problems using this as a package

### ISSUE THREAD

**Issue by lenborje** [mcmtilman/DancingLinks#1]
I'm trying to use this code as a package, i.e. I've created an Xcode project with a dependency to this repo. What I've done is basically to try to duplicate the Sudoku examples in a project which references the DancingLinks repo.

I've encountered several problems, some of which may well be due to my own incompetence (I admit both Swift and Xcode being rather new to me), but anyway I believe the following might genuine issues:

- I'd like to specify the dependency based on the version, but I believe the version tag should be pure semantic numbers, e.g. '1.0.0' instead of 'V1.0'.
- Several entities, e.g. `Grid`, `ClassyDancingLinks`, etc seem to be supposed to be used in public methods, but are not exported outside the package, since they are `internal`.

Perhaps you've not intended this to be used as package, or I'm doing something completely wrong?

Best regards

**Comment by mcmtilman** [comment]
Sorry for the late response, I completely missed this issue.

This project was extracted from a local XCode project (an older iOS Swift sudoku app - work in progress) to become a playground for tinkering with the algorithms and test via some examples (and I also wanted to try out Swift packages).

Anyway, I updated the code with a public interface for the algorithms, and with the examples as internal. This version has tag 1.2.0.

Regards,

michel

**Comment by lenborje** [comment]
Thank you for fixing this!
